version: "3"
services:

  nginx: 
    image: nginx:latest
    container_name: flwsb-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/site.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    restart: on-failure:10

  influxdb:
    container_name: flwsb-influxdb
    build:
      context: .
      dockerfile: ./influxdb/Dockerfile
    ports:
      - 127.0.0.1:8086:8086 # for debugging
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - TZ=${TIMEZONE}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=FLWSB
    restart: on-failure:10

  mosquitto:
    container_name: flwsb-mosquitto
    build:
      context: ./mosquitto
      dockerfile: ./Dockerfile
    ports:
      - 1883:1883
    volumes:
      - mosquitto:/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    environment:
      - TZ=${TIMEZONE}
      - MOSQUITTO_USER=${MOSQUITTO_USER}
      - MOSQUITTO_PASSWD=${MOSQUITTO_PASSWD}
    restart: on-failure:10

  grafana:
    container_name: flwsb-grafana
    image: grafana/grafana:latest
    depends_on:
      - nodered
      - influxdb
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWD}
      - GRAFANA_INFLUX_BUCKET=${INFLUXDB_BUCKET}
      - GRAFANA_INFLUX_TOKEN=${INFLUXDB_TOKEN}
      - GRAFANA_INFLUX_ORG=${INFLUXDB_ORG}
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    restart: on-failure:10

volumes:
  nodered:
  grafana:
  influxdb_data:
  mosquitto:
